import "~/styles/globals.css";
import { TopNav } from "../components/topnav"

import { Arimo } from "next/font/google";
import Footer from "~/components/footer";

const arimo = Arimo({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${arimo.variable} dark flex flex-col`}>
          <TopNav />
          <div className="2xl:w-3/4 xl:px-0 px-4 w-full flex-row self-center justify-between py-8">
            {children}
            <footer>
              <Footer />
            </footer>
          </div>
      </body>
      
    </html >
  );
}
