services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    container_name: flask_app
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db

  discord_bot:
    build: 
      context: ./discord_bot
      dockerfile: dsp_bot.dockerfile
    restart: always
    depends_on:
      - db
    environment:
     - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./discord_bot:/app/discord_bot
    command: python3 main.py

volumes:
  pgdata: {}